version: '3.3'

services:
  fhirserver1:
    image: ghcr.io/costateixeira/fhirserver:nightly
    volumes:
      - ./txcache:/var/cache/txcache
      - ./config:/root/fhirserver/config
    container_name: tx-fhir-eu
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DISPLAY=:99
      - DAEMON_MODE=-nodaemon
    tty: true
    command: ["bash", "-c", "./start.sh ${DAEMON_MODE}"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/r4/metadata"]
      interval: 5m
      timeout: 30s
      retries: 5
      start_period: 600s

